# Macros
CXX ?= g++
LDXX ?= g++
LDLIBS ?= -lncurses
CXXFLAGS ?= -Wall -pedantic -Wextra -g
MKDIR ?= mkdir
RM ?= rm
SOURCE_DIR ?= src
BUILD_DIR ?= build
GAME_NAME ?= antwars

# Rules
all: $(BUILD_DIR) $(GAME_NAME) doc

# Create directories
$(BUILD_DIR):
	$(MKDIR) -p $(BUILD_DIR)

.PHONY: compile
compile: $(BUILD_DIR) $(GAME_NAME)

.PHONY: run
run: $(BUILD_DIR) $(GAME_NAME)
	./$(GAME_NAME)
# Delete all files generated by compiler
.PHONY: clean
clean:
	$(RM) -r $(BUILD_DIR)
	$(RM) -R doc
	$(RM) $(GAME_NAME)

.PHONY: doc
doc:
	doxygen $(SOURCE_DIR)/Doxyconfig

$(GAME_NAME): $(BUILD_DIR)/main.o $(BUILD_DIR)/AAnt.o $(BUILD_DIR)/AMapObject.o $(BUILD_DIR)/CAnt.o $(BUILD_DIR)/CAntHill.o $(BUILD_DIR)/CAntQueen.o $(BUILD_DIR)/CEmptyTile.o $(BUILD_DIR)/CGameState.o $(BUILD_DIR)/CMap.o $(BUILD_DIR)/CMenu.o $(BUILD_DIR)/CObstacle.o
	$(LDXX) $(CXXFLAGS) -o $@ $^ $(LDLIBS)

$(BUILD_DIR)/%.o: $(SOURCE_DIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<


# Output of g++ -MM src/*.cpp >> Makefile

AAnt.o: src/AAnt.cpp src/AAnt.hpp src/AMapObject.hpp src/CAntHill.hpp \
 src/CAntQueen.hpp src/CAnt.hpp src/CMap.hpp
AMapObject.o: src/AMapObject.cpp src/AMapObject.hpp
CAnt.o: src/CAnt.cpp src/CAnt.hpp src/AAnt.hpp src/AMapObject.hpp \
 src/CAntHill.hpp src/CAntQueen.hpp src/CMap.hpp
CAntHill.o: src/CAntHill.cpp src/CAntHill.hpp src/AMapObject.hpp \
 src/AAnt.hpp src/CMap.hpp src/CAntQueen.hpp src/CAnt.hpp
CAntQueen.o: src/CAntQueen.cpp src/CAntQueen.hpp src/AAnt.hpp \
 src/AMapObject.hpp src/CAntHill.hpp src/CAnt.hpp src/CMap.hpp
CEmptyTile.o: src/CEmptyTile.cpp src/CEmptyTile.hpp src/AMapObject.hpp
CGameState.o: src/CGameState.cpp src/CGameState.hpp src/CMap.hpp \
 src/AMapObject.hpp src/CAntHill.hpp src/AAnt.hpp src/CAntQueen.hpp \
 src/CAnt.hpp src/Difficulty.hpp
CMap.o: src/CMap.cpp src/CMap.hpp src/AMapObject.hpp src/CAntHill.hpp \
 src/AAnt.hpp src/CAntQueen.hpp src/CAnt.hpp src/CEmptyTile.hpp
CMenu.o: src/CMenu.cpp src/CMenu.hpp src/CGameState.hpp src/CMap.hpp \
 src/AMapObject.hpp src/CAntHill.hpp src/AAnt.hpp src/CAntQueen.hpp \
 src/CAnt.hpp src/Difficulty.hpp src/CObstacle.hpp src/CEmptyTile.hpp
CObstacle.o: src/CObstacle.cpp src/CObstacle.hpp src/AMapObject.hpp
main.o: src/main.cpp src/CMenu.hpp src/CGameState.hpp src/CMap.hpp \
 src/AMapObject.hpp src/CAntHill.hpp src/AAnt.hpp src/CAntQueen.hpp \
 src/CAnt.hpp src/Difficulty.hpp src/CObstacle.hpp src/CEmptyTile.hpp
